output   = "models"
pkgname  = "models"
wipe     = true
no-tests = true
add-enum-types = true

[psql]
  host = "localhost"
  port = 5432
  user = "devuser"
  pass = "devpass"
  dbname = "dev"  
  sslmode = "disable"
  schema = "public"
  blacklist = ["schema_migrations"]
