version: '3'

vars:
  MIGRATIONS_PATH: ./migrations
  ENV: .env

dotenv: ['{{.ENV}}']

tasks:
  setup:
    cmds:
      - sh ./scripts/setup.sh

  dev:
    cmds:
      - godotenv -f {{.ENV}} go run .

  build:
    cmds:
      - task: gen-models
      - task: lint
      - task: test
      - go build .

  lint:
    cmds:
      - golangci-lint run ./...

  test:
    cmds:
      - godotenv -f {{.ENV}} go test -v ./...

  gen-models:
    cmds:
      - sqlboiler psql -c sqlboiler.toml

  # usage: NAME=create_sample_table task migration-create
  migration-create:
    cmds:
      - migrate create -ext sql -dir {{.MIGRATIONS_PATH}} -seq $NAME

  migrate-up:
    cmds:
      - migrate -path '{{.MIGRATIONS_PATH}}' -database $DB_CONNECTION -verbose up
      - task: gen-models

  migrate-drop:
    cmds:
      - migrate -path {{.MIGRATIONS_PATH}} -database $DB_CONNECTION drop
