// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	BookingResources   string
	Bookings           string
	Delivery           string
	SiteDays           string
	SiteResources      string
	SiteSubcontractors string
	SiteVendors        string
	Sites              string
	Users              string
	Vendors            string
}{
	BookingResources:   "booking_resources",
	Bookings:           "bookings",
	Delivery:           "delivery",
	SiteDays:           "site_days",
	SiteResources:      "site_resources",
	SiteSubcontractors: "site_subcontractors",
	SiteVendors:        "site_vendors",
	Sites:              "sites",
	Users:              "users",
	Vendors:            "vendors",
}
